server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

      routes:
        - id : API-SERVICE
          uri: http://api-service-svc
          predicates:
            - Path=//**

        - id: SCARPPER-SERVICE
          uri: http://scrapper-service-svc
          predicates:
            - Path=/scarper/**
